"use client";

import Image from "next/image";
import { useEffect, useRef, useState } from "react";

export default function Home() {
  const inputRef = useRef(null);
  const [text, setText] = useState("Hello from @vercel/og");

  useEffect(() => {
    inputRef.current.focus();
  }, []);

  return (
    <main className="flex min-h-screen flex-col items-center gap-16 p-16">
      <h1>ImageResponse practice</h1>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          setText(inputRef.current.value);
        }}
      >
        <input
          type="text"
          ref={inputRef}
          defaultValue={text}
          className="w-[300px] mb-4 p-2 border border-gray-300"
        />
      </form>
      <Image
        src={`/api/og?text=${text}`}
        alt="Generated by ImageResponse"
        width={800}
        height={400}
      />
    </main>
  );
}
