"use client";

import { Copy } from "lucide-react";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";

export default function Home() {
  const inputRef = useRef(null);
  const [text, setText] = useState("LGTM 😻");
  const copyText = `![LGTM-image](https://satori-image-response-practice.vercel.app/api/og?text=${encodeURIComponent(
    text
  )})`;

  useEffect(() => {
    inputRef.current.focus();
  }, []);

  function CopyText() {
    navigator.clipboard.writeText(copyText);
    alert("Copied!");
  }

  return (
    <main className="flex min-h-screen flex-col items-center gap-12 p-12 text-gray-700">
      <form
        onSubmit={(e) => {
          e.preventDefault();
          setText(inputRef.current.value);
        }}
      >
        <label className="block mb-1">👇 input here!</label>
        <input
          type="text"
          ref={inputRef}
          defaultValue={text}
          className="w-[300px] p-2 border border-gray-300 rounded"
        />
      </form>
      <Image
        src={`/api/og?text=${text}`}
        alt="Generated by ImageResponse"
        width={600}
        height={360}
      />
      <div className="flex gap-2 justify-center items-center">
        <input
          type="text"
          value={copyText}
          className="w-[300px] p-2 border border-gray-300 rounded"
        />
        <button
          className="hover:bg-fuchsia-50 rounded-lg p-2"
          onClick={CopyText}
        >
          <Copy />
        </button>
      </div>
    </main>
  );
}
